### ISSUE TITLE
Scale down Greenlands

### ISSUE THREAD

**Issue by tupini07** [microsoft/greenlands#6]
`Greenlands` was originally developed with the goal of having a shared platform where many teams can organize _tournaments_ with different tasks, and all share a pool of human users that play in those tasks against each other or against AI agents.

Now, this might no longer be the best use case for this project going forward. It would be more useful if it were possible for anyone to take the code here and deploy their own Minecraft server separately. This would simplify the setup process (and the code architecture) quite a bit, but there is some considerable work to get this done.

```[tasklist]
### Tasks
- [ ] Plugin directly stores task.json information as resources
- [ ] Agents communicate with Plugin via websockets (remove dependency on Event Hub)
- [ ] Plugin saves game information in local SQLite DB. Game events are logged to separate files
- [ ] Remove concept of tournament, and human and agent challenges
- [ ] Remove dependency on Service (need to move "Models" somewhere else)
```
